// Generated by scripts/write-prod-environment.mjs — do not edit manually.
import type { AppEnvironment } from './environment.types';

export const environment: AppEnvironment = {
  production: true,
  supabaseUrl: '',
  supabasePublishableKey: '',
  appUrl: '',
  platformHosts: [],
  cookieParentDomain: '',
  tenantHostSuffix: '',
};
